language: csharp
mono: none
dotnet: 2.1

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test --logger:xunit --logger:"console;verbosity=detailed" Kollavarsham.Net.Tests/Kollavarsham.Net.Tests.csproj