language: csharp
mono: none
dotnet: 2.1

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test --logger:xunit --logger:"console;verbosity=detailed" /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/lcov.info ./Kollavarsham.Net.Tests